# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-20 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudasaService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='title_content',
            field=models.TextField(max_length=6000, null=True),
        ),
    ]
